import Head from "next/head";
import { textContent } from "../constants";

export default function Index(): JSX.Element {
  return (
    <>
      <Head>
        <title>{textContent.homepage.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen dark:bg-gray-900">
        <main className="order-2 mx-4 mt-4 mb-24 flex-[1_0_16rem]">
          <div>arre</div>
        </main>
      </div>
    </>
  );
}
